In [68]:
import pandas  as  pd
data =pd.read_csv("50_Startups.csv")
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [69]:
data =pd.get_dummies(data=data,columns=['State'],drop_first=True)
data[['State_Florida','State_New York']]  =data[['State_Florida','State_New York']].astype(int)
data.head() #one-hot encoding

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0

In [70]:
y=data['Profit'].values
x=data.drop('Profit',axis=1).values

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [71]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [72]:
from sklearn.decomposition import PCA
decomp = PCA(n_components=3)
x_train = decomp.fit_transform(x_train)
x_test = decomp.transform(x_test)
#reducing dimensions

In [73]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
print(model.score(x_test,y_test))
print(sum(decomp.explained_variance_ratio_))

0.8313539156423422
0.8558523113264889

In [74]:

original_data = pd.read_csv("50_Startups.csv")
original_data['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)