In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from keras.models import Sequential
from keras.layers import Dense


data=pd.read_csv("/content/diamonds.csv")

data.head()

   carat  depth  table  price     x     y     z
0   0.23   61.5   55.0    326  3.95  3.98  2.43
1   0.21   59.8   61.0    326  3.89  3.84  2.31
2   0.23   56.9   65.0    327  4.05  4.07  2.31
3   0.29   62.4   58.0    334  4.20  4.23  2.63
4   0.31   63.3   58.0    335  4.34  4.35  2.75

In [23]:
data['diagonal']=np.sqrt((data['x']**2)+(data['y']**2)+(data['z']**2))
data.drop(['x','y','z'],axis=1,inplace=True)
data['price']=np.log10(data['price'])
data.head()

   carat  depth  table     price  diagonal
0   0.23   61.5   55.0  2.513218  6.111285
1   0.21   59.8   61.0  2.513218  5.934122
2   0.23   56.9   65.0  2.514548  6.188982
3   0.29   62.4   58.0  2.523746  6.515351
4   0.31   63.3   58.0  2.525045  6.732058

In [24]:
y=data['price'].values
x=data.drop('price',axis=1).values
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

pca=PCA(n_components=2)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)

model=Sequential()

model.add(Dense(units=30,activation='relu',input_dim=x_train.shape[1]))


model.add(Dense(units=30,activation='relu'))
model.add(Dense(units=30,activation='relu'))
model.add(Dense(units=30,activation='relu'))
model.add(Dense(units=30,activation='relu'))
model.add(Dense(units=30,activation='relu'))


model.add(Dense(units=1,activation='linear'))


model.compile(optimizer="adam",loss="mse",metrics=['mae'])

model.fit(x_train,y_train,epochs=30,batch_size=43,validation_data=(x_test,y_test),verbose=1)
#

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 0.4307 - mae: 0.2447 - val_loss: 0.0125 - val_mae: 0.0884
Epoch 2/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0130 - mae: 0.0901 - val_loss: 0.0124 - val_mae: 0.0871
Epoch 3/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0131 - mae: 0.0905 - val_loss: 0.0164 - val_mae: 0.1016
Epoch 4/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0134 - mae: 0.0913 - val_loss: 0.0127 - val_mae: 0.0884
Epoch 5/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0135 - mae: 0.0917 - val_loss: 0.0127 - val_mae: 0.0890
Epoch 6/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 0.0135 - mae: 0.0916 - val_loss: 0.0123 - val_mae: 0.0873
Epoch 7/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0134 - mae: 0.0913 - val_loss: 0.0135 - val_mae: 0.0920
Epoch 8/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0134 - mae: 0.0915 - val_loss: 0.0133 - val_mae: 0.0910
Epoch 9/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0132 - mae: 0.0909 - val_loss: 0.0122 - val_mae: 0.0871
Epoch 10/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 0.0134 - mae: 0.0912 - val_loss: 0.0141 - val_mae: 0.0943
Epoch 11/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0134 - mae: 0.0912 - val_loss: 0.0166 - val_mae: 0.1029
Epoch 12/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0133 - mae: 0.0911 - val_loss: 0.0124 - val_mae: 0.0878
Epoch 13/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0131 - mae: 0.0903 - val_loss: 0.0150 - val_mae: 0.0975
Epoch 14/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0132 - mae: 0.0905 - val_loss: 0.0140 - val_mae: 0.0934
Epoch 15/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 0.0130 - mae: 0.0902 - val_loss: 0.0121 - val_mae: 0.0864
Epoch 16/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0132 - mae: 0.0907 - val_loss: 0.0147 - val_mae: 0.0955
Epoch 17/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0131 - mae: 0.0902 - val_loss: 0.0168 - val_mae: 0.1038
Epoch 18/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0131 - mae: 0.0905 - val_loss: 0.0121 - val_mae: 0.0869
Epoch 19/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0129 - mae: 0.0896 - val_loss: 0.0175 - val_mae: 0.1060
Epoch 20/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.0130 - mae: 0.0900 - val_loss: 0.0123 - val_mae: 0.0877
Epoch 21/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0129 - mae: 0.0895 - val_loss: 0.0121 - val_mae: 0.0861
Epoch 22/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0131 - mae: 0.0904 - val_loss: 0.0137 - val_mae: 0.0925
Epoch 23/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0131 - mae: 0.0902 - val_loss: 0.0124 - val_mae: 0.0876
Epoch 24/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0129 - mae: 0.0896 - val_loss: 0.0127 - val_mae: 0.0890
Epoch 25/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0130 - mae: 0.0898 - val_loss: 0.0131 - val_mae: 0.0896
Epoch 26/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0129 - mae: 0.0894 - val_loss: 0.0121 - val_mae: 0.0871
Epoch 27/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0129 - mae: 0.0896 - val_loss: 0.0121 - val_mae: 0.0862
Epoch 28/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0129 - mae: 0.0896 - val_loss: 0.0121 - val_mae: 0.0868
Epoch 29/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0130 - mae: 0.0897 - val_loss: 0.0134 - val_mae: 0.0916
Epoch 30/30
1004/1004 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0130 - mae: 0.0900 - val_loss: 0.0128 - val_mae: 0.0893